[package]
name = "zappy-rs"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/GodlyJaaaj/zappy-rs"
rust-version = "1.82.0"
keywords = ["zappy", "zappy-rs", "multithreaded", "blazing-fast", "epitech"]
default-run = "zappy-rs"

[[bin]]
name = "zappy-rs"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.42.0", features = ["full"] }
rand = "0.9.0-beta.1"
